### ISSUE TITLE
Light vs Dark theme

### ISSUE THREAD

**Issue by zigomir** [celtra/stateless-components#29]
Currently one cannot simply change theme from `dark` to `light` in a prop input [because of this](https://github.com/celtra/stateless-components/blob/377c2f96bf3f46a166492529ff455f11a3bc3255/src/components/ComponentsList.vue#L82) code. Besides, we'd have to change a body background color as well.

I suggest that we move `theme` to be a global state that `component-list` reacts on and changes background `body` css to: 

```less
background-color: @very-dark-gray;
color: white;
```

and sets `theme` on `component-list`. This way product people can review both themes with single deploy.

@zan-kusterle or @kurent  Would you take such change if I did a PR?

p.s.: I asked Jurij V. to turn Issues feature on this repo ;)

**Comment by kurent** [comment]
Yes, I guess this would be a reasonable thing to do. I can do a CR.
