### ISSUE TITLE
Auto deploy for `master` branch and pull requests

### ISSUE THREAD

**Issue by zigomir** [celtra/stateless-components#72]
@zan-kusterle @kurent 

Is there an effort going on to deploy "demo page" somewhere? I'm clashing with QA on reporting issues I believe are in there **by design** and would be helpful if I can give them URL and **prove** it is by design – [reference](https://celtra.atlassian.net/browse/MAB-14108).

There are lots of tools outside today, I especially like [now](https://zeit.co/now) where they support GitHub integration and deploys for every PR.

If there's no effort yet and you don't object to do it with `now`, let me know and I'll take care of it.

**Comment by zan-kusterle** [comment]
There is no effort currently since we're still busy with report builder, so I guess we can use `now` for now.
